USE [cabs_production]
GO

/****** Object:  StoredProcedure [dbo].[LicenceMasterVLAudit_Insert]    Script Date: 5/6/2020 10:32:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[LicenceMasterVLAudit_Insert]

@PlateNumber int,
@LicenceNumber varchar(50),
@LicenceHolderId int,
@RegistrationNumber varchar(50),
@LicenceTypeId tinyint,
@LicenceStateId tinyint,
@LicenceStateMasterId tinyint,
@LicenceExpiryDate smalldatetime,
@LicenceIssueDate smalldatetime,
@CoExpiryDate smalldatetime,
@CoIssueDate smalldatetime,
@RenewalDate smalldatetime,
@TransferedFromReg varchar(50),
@HistoryChangeId tinyint,
@TestCenterId smallint,
@RemainingTransfers int,
@TransferDate smalldatetime,
@OldPlateNumber varchar(50),
@OldLicenceAuthority varchar(50),
@Ccsn nvarchar(10),
@Ppsn varchar(10),
@CompanyNumber int,
@FirstName nvarchar(50),
@LastName nvarchar(50),
@DateOfBirth datetime,
@CompanyName nvarchar(50),
@TradingAs nvarchar(50),
@AddressLine1 nvarchar(50),
@AddressLine2 nvarchar(50),
@AddressLine3 nvarchar(50),
@Town nvarchar(50),
@CountyId tinyint,
@PostCode varchar(10),
@CountryId smallint,
@PhoneNo1 varchar(15),
@PhoneNo2 varchar(15),
@Email nvarchar(50),
@TaxClearanceNumber varchar(20),
@TaxClearanceCertExists bit,
@TaxClearanceName nvarchar(100),
@CreatedBy nvarchar(50),	
@CreatedDate datetime,	
@ModifiedBy nvarchar(50),	
@ModifiedDate datetime,
@LAHArea nvarchar(100),
@Director1Name nvarchar(100),
@Director2Name nvarchar(100),
@Director3Name nvarchar(100),
@Director1Address nvarchar(150),
@Director2Address nvarchar(150),
@Director3Address nvarchar(150),
@SuspensionStartDate datetime,
@SuspensionEndDate datetime,
@EVGrantStatusId int,
@EVGrantExpiryDate smalldatetime,
@WAVGrantStatusId int,
@WAVGrantExpiryDate smalldatetime,
@AreaOfOpperations nvarchar(255) null,
@WebSite nvarchar(255) null,
@NumberForBookings varchar(20) null,
@DispatchOperatorId int null,
@EmailAddressForBooking nvarchar(255) null
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

INSERT INTO LicenceMasterVLAudit
(
PlateNumber,
LicenceNumber,
LicenceHolderId,
RegistrationNumber,
LicenceTypeId,
LicenceStateId,
LicenceStateMasterId,
LicenceExpiryDate,
LicenceIssueDate,
CoExpiryDate,
CoIssueDate,
RenewalDate,
TransferedFromReg,
HistoryChangeId,
TestCenterId,
RemainingTransfers,
TransferDate,
OldPlateNumber,
OldLicenceAuthority,
Ccsn,
Ppsn,
CompanyNumber,
FirstName,
LastName,
DateOfBirth,
CompanyName,
TradingAs,
AddressLine1,
AddressLine2,
AddressLine3,
Town,
CountyId,
PostCode,
CountryId,
PhoneNo1,
PhoneNo2,
Email,
TaxClearanceNumber,
TaxClearanceCertExists,
TaxClearanceName,
CreatedBy,
CreatedDate,
ModifiedBy,
ModifiedDate,
AuditDate,
LAHArea,
Director1Name,
Director2Name,
Director3Name,
Director1Address,
Director2Address,
Director3Address,
SuspensionStartDate,
SuspensionEndDate,
EVGrantStatusId,
EVGrantExpiryDate,
WAVGrantStatusId,
WAVGrantExpiryDate,
AreaOfOpperations,
Website,
NumberForBookings,
DispatchOperatorId,
EmailAddressForBooking
)

VALUES
(
@PlateNumber,
@LicenceNumber,
@LicenceHolderId,
@RegistrationNumber,
@LicenceTypeId,
@LicenceStateId,
@LicenceStateMasterId,
@LicenceExpiryDate,
@LicenceIssueDate,
@CoExpiryDate,
@CoIssueDate,
@RenewalDate,
@TransferedFromReg,
@HistoryChangeId,
@TestCenterId,
@RemainingTransfers,
@TransferDate,
@OldPlateNumber,
@OldLicenceAuthority,
@Ccsn,
@Ppsn,
@CompanyNumber,
@FirstName,
@LastName,
@DateOfBirth,
@CompanyName,
@TradingAs,
@AddressLine1,
@AddressLine2,
@AddressLine3,
@Town,
@CountyId,
@PostCode,
@CountryId,
@PhoneNo1,
@PhoneNo2,
@Email,
@TaxClearanceNumber,
@TaxClearanceCertExists,
@TaxClearanceName,
@CreatedBy,
@CreatedDate,
@ModifiedBy,
@ModifiedDate,
Getdate(),
@LAHArea,
@Director1Name,
@Director2Name,
@Director3Name,
@Director1Address,
@Director2Address,
@Director3Address,
@SuspensionStartDate,
@SuspensionEndDate,
@EVGrantStatusId,
@EVGrantExpiryDate,
@WAVGrantStatusId,
@WAVGrantExpiryDate,
@AreaOfOpperations,
@WebSite,
@NumberForBookings,
@DispatchOperatorId,
@EmailAddressForBooking
)
    -- Insert statements for procedure here

END

GO

