USE [cabs_live]
GO

/****** Object:  Table [dbo].[GrantCheck]    Script Date: 23.05.2022 14:25:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GrantCheck](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GrantId] [int] NOT NULL,
	[CheckType] [nvarchar](50) NOT NULL,
	[CheckDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_GrantCheck] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_GrantId_CheckType] UNIQUE NONCLUSTERED 
(
	[GrantId] ASC,
	[CheckType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GrantCheck]  WITH CHECK ADD  CONSTRAINT [FK_GrantDetails_GrantCheck] FOREIGN KEY([GrantId])
REFERENCES [dbo].[GrantDetails] ([Id])
GO

ALTER TABLE [dbo].[GrantCheck] CHECK CONSTRAINT [FK_GrantDetails_GrantCheck]
GO


