
USE [cabs_production]

insert [do].[CountyOfOperator] ([Id],[Name],[CreatedDate],[CreatedBy],[ModifiedDate],[ModifiedBy])
select 1,N'CARLOW',GETDATE(),N'System',NULL,NULL UNION ALL
select 2,N'CAVAN',GETDATE(),N'System',NULL,NULL UNION ALL
select 3,N'CLARE',GETDATE(),N'System',NULL,NULL UNION ALL
select 4,N'CORK',GETDATE(),N'System',NULL,NULL UNION ALL
select 5,N'DONEGAL',GETDATE(),N'System',NULL,NULL UNION ALL
select 6,N'DUBLIN',GETDATE(),N'System',NULL,NULL UNION ALL
select 7,N'GALWAY',GETDATE(),N'System',NULL,NULL UNION ALL
select 8,N'KERRY',GETDATE(),N'System',NULL,NULL UNION ALL
select 9,N'KILDARE',GETDATE(),N'System',NULL,NULL UNION ALL
select 10,N'KILKENNY',GETDATE(),N'System',NULL,NULL UNION ALL
select 11,N'LAOIS',GETDATE(),N'System',NULL,NULL UNION ALL
select 12,N'LEITRIM',GETDATE(),N'System',NULL,NULL UNION ALL
select 13,N'LIMERICK',GETDATE(),N'System',NULL,NULL UNION ALL
select 14,N'LONGFORD',GETDATE(),N'System',NULL,NULL UNION ALL
select 15,N'LOUTH',GETDATE(),N'System',NULL,NULL UNION ALL
select 16,N'MAYO',GETDATE(),N'System',NULL,NULL UNION ALL
select 17,N'MEATH',GETDATE(),N'System',NULL,NULL UNION ALL
select 18,N'MONAGHAN',GETDATE(),N'System',NULL,NULL UNION ALL
select 19,N'OFFALY',GETDATE(),N'System',NULL,NULL UNION ALL
select 20,N'ROSCOMMON',GETDATE(),N'System',NULL,NULL UNION ALL
select 21,N'SLIGO',GETDATE(),N'System',NULL,NULL UNION ALL
select 22,N'TIPPERARY',GETDATE(),N'System',NULL,NULL UNION ALL
select 23,N'WATERFORD',GETDATE(),N'System',NULL,NULL UNION ALL
select 24,N'WESTMEATH',GETDATE(),N'System',NULL,NULL UNION ALL
select 25,N'WEXFORD',GETDATE(),N'System',NULL,NULL UNION ALL
select 26,N'WICKLOW',GETDATE(),N'System',NULL,NULL;

